In [ ]:
#simple content based recommender - runs on all data and returns recommendations from all cities

In [1]:
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive


In [2]:
import pandas as pd
import numpy as np 
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
file = pd.read_csv("/content/gdrive/My Drive/entree.csv")
file.head()

Index  ...                               RestaurantAttributes
0      0  ...  American (Traditional) Catering for Special Ev...
1      1  ...  Good Decor Dining After the Theater Dining Out...
2      2  ...  Catering for Special Events Fair Decor Deliver...
3      3  ...  Catering for Special Events Chinese Good Decor...
4      4  ...  American (Contemporary) American (Traditional)...

[5 rows x 5 columns]

In [4]:
file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4160 entries, 0 to 4159
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   Index                 4160 non-null   int64 
 1   RestaurantID          4160 non-null   object
 2   RestaurantName        4160 non-null   object
 3   RestaurantCity        4160 non-null   object
 4   RestaurantAttributes  4160 non-null   object
dtypes: int64(1), object(4)
memory usage: 162.6+ KB


In [5]:
file.isnull().sum()

Index                   0
RestaurantID            0
RestaurantName          0
RestaurantCity          0
RestaurantAttributes    0
dtype: int64

In [6]:
file.columns

Index(['Index', 'RestaurantID', 'RestaurantName', 'RestaurantCity',
       'RestaurantAttributes'],
      dtype='object')

### Adding new column which contrains string of all features

In [ ]:
#ended up doing this in excel, but kept code to maintain original script

In [7]:
def combined_features(row):
    return row["RestaurantAttributes"]

In [8]:
file["combined_features"] = file.apply(combined_features, axis=1)

In [9]:
#file.iloc[71,:]

In [10]:
file["combined_features"][0]

'American (Traditional) Catering for Special Events Good Decor Delivery Available Dining Outdoors Good Food Good for Younger Kids below $15 Parking/Valet People Keep Coming Back Good Service Weekend Dining Wheelchair Access '

### Computing the cosine similarity after vectorizing features

In [11]:
cv = CountVectorizer()
count_matrix = cv.fit_transform(file["combined_features"])
#print(count_matrix) #it can also be converted to numpy array by count_matrix.toarray()


In [12]:
cos_sim = cosine_similarity(count_matrix)
print(cos_sim)

[[1.         0.56114254 0.57789674 ... 0.42163702 0.44798934 0.37796447]
 [0.56114254 1.         0.47079191 ... 0.49377072 0.58635273 0.47951222]
 [0.57789674 0.47079191 1.         ... 0.63564173 0.44494921 0.56980288]
 ...
 [0.42163702 0.49377072 0.63564173 ... 1.         0.56666667 0.67729621]
 [0.44798934 0.58635273 0.44494921 ... 0.56666667 1.         0.67729621]
 [0.37796447 0.47951222 0.56980288 ... 0.67729621 0.67729621 1.        ]]


In [13]:
def get_index(name):
    return file[file["RestaurantName"] == name]["Index"].values[0]
def get_restaurant(index):
    return file[file["Index"] == index]["RestaurantName"].values[0]
def get_restaurant_city(index):
    return file[file["Index"] == index]["RestaurantCity"].values[0]


In [15]:
entername = input("Enter your favourite restaurant:")
restaurant_index = get_index(entername)
similiar_restaurants = list(enumerate(cos_sim[restaurant_index]))

Enter your favourite restaurant:Moti Mahal


In [16]:
sorted_restaurants = sorted(similiar_restaurants,key=lambda x:x[1],reverse=True)
sorted_restaurants

[(705, 1.0000000000000002),
 (1369, 0.9000000000000001),
 (1338, 0.8000000000000002),
 (966, 0.7905694150420951),
 (1225, 0.7905694150420951),
 (1353, 0.7905694150420951),
 (1173, 0.790569415042095),
 (881, 0.7826237921249266),
 (980, 0.7606388292556651),
 (1109, 0.7592566023652967),
 (912, 0.7510409442899901),
 (974, 0.7505553499465136),
 (3927, 0.7505553499465136),
 (502, 0.7500000000000001),
 (1092, 0.7500000000000001),
 (1373, 0.7500000000000001),
 (942, 0.7442084075352509),
 (771, 0.7378647873726221),
 (1215, 0.7319250547113998),
 (1371, 0.7319250547113998),
 (548, 0.7302967433402218),
 (1064, 0.7302967433402218),
 (1284, 0.7302967433402218),
 (1303, 0.7155417527999327),
 (859, 0.7150969419341943),
 (981, 0.7150969419341943),
 (1179, 0.6993786061802353),
 (1264, 0.6993786061802353),
 (1293, 0.6993786061802353),
 (760, 0.6928203230275509),
 (540, 0.685160159703149),
 (581, 0.6831300510639732),
 (1226, 0.6761234037828133),
 (764, 0.674199862463242),
 (956, 0.674199862463242),
 (741,

In [17]:
top_matched = []
for i in sorted_restaurants:
    if i[1] > 0.1:
        top_matched.append(i[0])
        

In [18]:
recommended_restaurants = []
for i in top_matched:
    recommended_restaurant_cities = []
    recommended_restaurant_cities.append(get_restaurant_city(i))
    for item in recommended_restaurant_cities:
        if item == "Chicago":
            recommended_restaurants.append(get_restaurant(i))
    

In [19]:
for i in recommended_restaurants:
    print(i)
    print("----")

Moti Mahal
----
Standard India
----
Udupi Palace
----
Old Jerusalem
----
Hashalom
----
Formosa
----
August Moon
----
Mei Shung
----
Penny's Noodle Shop
----
Hau Giang
----
El Presidente
----
Thai Star Cafe
----
Anna Maria Pasteria
----
Pine Yard
----
Gandhi Indian
----
Thai Classic
----
Pierogi Inn
----
Tulpe
----
Dave's Italian Kitchen
----
Three Happiness
----
Edith's Bar-B-Q
----
Natraj
----
Lanna Thai
----
La Creperie
----
Cousin's
----
P.S. Bangkok
----
Kanval Palace
----
Leo's Lunchroom
----
Ha Mien
----
Nhu Hoa Cafe
----
Sukumvit Cafe
----
Hi Howe
----
Fondue Stube
----
Shree
----
Machu Picchu
----
Ambassador Caffe
----
Tien Tsin
----
Mozart Cafe
----
Seven Treasures
----
Cafe Borgia
----
El Dinamico Dallas
----
Poolgogi House
----
Soul Kitchen
----
Healthy Food
----
Rim Klong
----
Bangkok Star
----
Mama Desta's Red Sea
----
Tehran
----
Mekong
----
Fernando's
----
Abbis Abeba
----
Lac Vien
----
Tre Kronor
----
Noodle Noodle
----
Song Huong
----
Korean Restaurant
----
Alex's Wash

In [ ]:
#Only print top 10 recommendations

In [20]:
for i in recommended_restaurants[:10]:
    print(i)
    print("----")

Moti Mahal
----
Standard India
----
Udupi Palace
----
Old Jerusalem
----
Hashalom
----
Formosa
----
August Moon
----
Mei Shung
----
Penny's Noodle Shop
----
Hau Giang
----
